# Generated by Django 4.1.4 on 2022-12-15 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("user", models.CharField(blank=True, max_length=100, unique=True)),
                ("section", models.CharField(blank=True, max_length=100)),
                ("floor", models.CharField(blank=True, max_length=100)),
                ("office", models.CharField(blank=True, max_length=100)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_list",
                        to="equipment.group",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
