# Generated by Django 4.1.4 on 2022-12-15 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_equipment_manufacturer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"ordering": ("name",), "verbose_name_plural": "equipment"},
        ),
        migrations.CreateModel(
            name="Ink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("count", models.PositiveIntegerField(default=1)),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ink_list",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
