# Generated by Django 4.1.4 on 2022-12-15 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0004_alter_equipment_options_ink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ink",
            name="printer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ink_list",
                to="equipment.equipment",
            ),
        ),
    ]
