# Generated by Django 4.1.4 on 2022-12-15 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_alter_ink_printer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ink",
            options={"ordering": ("name",), "verbose_name_plural": "ink"},
        ),
    ]
