# Generated by Django 4.1.4 on 2022-12-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0006_alter_ink_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="floor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ground", "Ground"),
                    ("First", "1st"),
                    ("Second", "2nd"),
                    ("Third", "3rd"),
                ],
                max_length=100,
            ),
        ),
    ]
